version: '3.9'
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  order:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379

  inventory:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  notification:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
